### ISSUE TITLE
Gem Guideline link is stale

### ISSUE THREAD

**Issue by chawes13** [LaunchPadLab/decanter#106]
## Expected Behavior
- Link goes to public Guidelines document

## Current Behavior
- Link goes to private repo with content that has been moved

## Steps to Reproduce
Open a PR and click the versioning guidelines link in the description

## Suggested Solution
Update with https://github.com/LaunchPadLab/opex-public/blob/master/gists/gem-guidelines.md#pull-requests-and-deployments

**Comment by priyamm** [comment]
@chawes13 this link is also not working, https://github.com/LaunchPadLab/opex/blob/master/gists/gem-guidelines.md#pull-requests-and-deployments

**Comment by chawes13** [comment]
@priyamm Great catch! Just updated

**Comment by chawes13** [comment]
Resolved by #108
