### ISSUE TITLE
symbol parser?

### ISSUE THREAD

**Issue by dianacamacho** [LaunchPadLab/decanter#113]
## Feature Description

Thoughts on adding a symbol parser to the default parsers? not sure how common it is for others, but i sometimes end up taking the incoming string params and converting that to a symbol when passing params along to other service classes

## Suggested Solution
```ruby
module Decanter
  module Parser
    class SymbolParser < ValueParser
      REGEX = /\s+/

      parser do |val, options|
        raise Decanter::ParseError.new 'Expects a single value' if val.is_a? Array
        next if (val.nil? || val === '')
        val.gsub(REGEX, "_").downcase.to_sym 
      end
    end
  end
end
```

## Alternatives Considered / Existing Workarounds
adding a custom parser in each app as needed

**Comment by chawes13** [comment]
The code that you've linked above is doing more than just converting to a symbol, right? I think I would expect the result that you're looking for here to be expressed via chained parses, e.g., `input :action, [:underscore, :symbol]`. The current set of default parsers are really more about parsing, not transforming values, so if we were to include it in the lib I think it should be limited to:
```rb
val.to_sym rescue val # from the source of https://apidock.com/rails/Hash/symbolize_keys
```
Would you still find this feature desirable? I wonder what you think about enhancing `StringParser` to accept `parse_format` options like `underscore`, `camelize`, etc.?

**Comment by chawes13** [comment]
@dianacamacho Have you found the need to include this custom parser and new / more projects recently?

**Comment by dianacamacho** [comment]
@chawes13 not really, i think we can close this. though the `StringParser` format options does sounds interesting.
