### ISSUE TITLE
Implicit collection detection only works via ActiveRecord extensions

### ISSUE THREAD

**Issue by chawes13** [LaunchPadLab/decanter#116]
## Environment

- `decanter` version: 3.4.0
- `ruby` version: 2.6.5
- `rails` version: 5.2.3

## Expected Behavior
`TodoDecanter.decant([{ title: 'Go for a run', completed: false }, { title: 'Eat fettuccine', completed: true }])` returns a collection of decanted objects

## Current Behavior
```sh
TypeError: wrong element type ActionController::Parameters at 0 (expected array)
from /Users/chawes/Documents/LaunchPad/opex/decanter/lib/decanter/core.rb:234:in `to_h'
```

## Steps to Reproduce
Call a decanter's `decant` method directly in a controller (i.e., do not use the ActiveRecord model class method extensions)

## Suggested Solution
- Move the implicit collection detection to Decanter `core.rb`
  - This requires some investigation to see how ActiveRecord behaves with collections for `new`, `create`, and `update`

**Comment by chawes13** [comment]
@inveterateliterate FYI. Let me know if this is surprising to you / doesn't meet your expectations based on your work in #111

**Comment by inveterateliterate** [comment]
hm yes this is kind of surprising to me. I suppose I tested the methods added but did not run this in a real application environment

**Comment by chawes13** [comment]
Would you mind pulling this into an existing local app or rails new to confirm?
