### ISSUE TITLE
Extraneous params keys no longer ignored

### ISSUE THREAD

**Issue by dianacamacho** [LaunchPadLab/decanter#120]
It seems like decanter is no longer truly decanting 🤔  It's parsing the desired keys but still retains all other params in the result. 

Before the rewrite (eg: v `1.1.8`), keys not explicitly included in the decanter file were ignored, leaving only the desired param keys in the decanted result (when old `strict` mode = true, meaning don't raise an exception for unhandled keys, but rather ignore them). It seems the only way to ignore keys now is to explicitly set a key as `ignored` in the decanter, which doesn't really makes sense if I just want to pass in all rails controller params as is.

Not sure if this was intentional or not? I would think not, since that kinda seems like the point of "decanting", to remove the irrelevant data. 

## Environment
Omaha API
- `decanter` version: 3.4.2
- `ruby` version: 2.5.0
- `rails` version: 5.1.4 

Trip-Decanter-Test
- `decanter` version: 3.4.2 / 1.1.10
- `ruby` version: 2.6.5
- `rails` version: 6.0.3.4

## Expected Behavior
Any keys not declared in the decanter should be ignored if strict is false

```ruby
class TripDecanter < Decanter::Base
  strict false # new v3 meaning of strict (meaning don't raise an exception)

  input :name, :string
  input :start_date, :date, parse_format: '%Y-%m-%d'
end
```

```ruby
params = { name: 'Spring Break', start_date: '2021-03-15', ignore: 'ignore' }

TripDecanter.decant(params)
=> { name: 'Spring Break', start_date: '2021-03-15' } # ignore key should be left out
```

Previously calling the decanter would also let you know that unhandled keys were being ignored in the logs

## Current Behavior
Keys not declared in the decanter are being returned in the decanted result

```ruby
TripDecanter.decant(params)
=> { name: 'Spring Break', start_date: '2021-03-15' , ignore: 'ignore' } # ignore key shouldn't exist
```

## Steps to Reproduce
[Trip Decanter Test repo ](https://github.com/dianacamacho/trip-decanter-test)
- `git clone git@github.com:dianacamacho/trip-decanter-test.git`
- `cd trip-decanter-test`
- enter `rails console` with `TripDecanter` behavior example above
- old behavior is on latest `main` commit
- v3 unhandled keys issue is on previous commit `git checkout d952f43c0e440a090e58812adb78972a39e1f6ba`

## Suggested Solution

the cause seems to be that the ignoring step was removed from the `unhandled_keys` method in `core.rb`. The option now is either strict true (default, exception raised for unhandled keys) or if strict is set to false, unhandled keys are always included in the result. 

Maybe we can add back the old middle check for ignoring? or remove the` .to_sym` part from the v3 method, so the unhandled keys are always ignored?

pre v3 

```ruby
      
      def unhandled_keys(args)
        unhandled_keys = args.keys.map(&:to_sym) -
          handlers.keys.flatten.uniq -
          keys_to_ignore -
          handlers.values
            .select { |handler| handler[:type] != :input }
            .map { |handler| "#{handler[:name]}_attributes".to_sym }            

        if unhandled_keys.any?
          case strict_mode
          when true
            p "#{self.name} ignoring unhandled keys: #{unhandled_keys.join(', ')}." # this part is no longer happening
            {}
          when :with_exception            
            raise(UnhandledKeysError, "#{self.name} received unhandled keys: #{unhandled_keys.join(', ')}.")
          else
            args.select { |key| unhandled_keys.include? key }
          end
        else
          {}
        end
      end
   ```
   
   current v 3.4.2
   
   ```ruby
      def unhandled_keys(args)
        unhandled_keys = args.keys.map(&:to_sym) -
          handlers.keys.flatten.uniq -
          keys_to_ignore -
          handlers.values
            .select { |handler| handler[:type] != :input }
            .map { |handler| "#{handler[:name]}_attributes".to_sym }

        return {} unless unhandled_keys.any?
        raise(UnhandledKeysError, "#{self.name} received unhandled keys: #{unhandled_keys.join(', ')}.") if strict_mode
        args.select { |key| unhandled_keys.include? key.to_sym }
      end
```   

Change Options:
1. maybe go back to original method but add third option for `strict_mode = :ignore`. So 
- strict = true (default), raises an exception
- strict = :ignore, exclude unhandled keys (previous strict = true behavior)
- strict = false, passes all params including unhandled keys (current behavior)

```ruby
      def strict(mode)
        raise(ArgumentError, "#{self.name}: Unknown strict value #{mode}") unless [true, false, :ignore].include? mode
        @strict_mode = mode
      end
      
      def unhandled_keys(args)
        unhandled_keys = args.keys.map(&:to_sym) -
          handlers.keys.flatten.uniq -
          keys_to_ignore -
          handlers.values
            .select { |handler| handler[:type] != :input }
            .map { |handler| "#{handler[:name]}_attributes".to_sym }            

        if unhandled_keys.any?
          case strict_mode
          when :ignore
            p "#{self.name} ignoring unhandled keys: #{unhandled_keys.join(', ')}."
            {}
          when true           
            raise(UnhandledKeysError, "#{self.name} received unhandled keys: #{unhandled_keys.join(', ')}.")
          else
            args.select { |key| unhandled_keys.include? key.to_sym }
          end
        else
          {}
        end
      end
   ```

OR just default to always "decanting" and thus always removing unhandled keys when strict is false?

```ruby

      def unhandled_keys(args)
        unhandled_keys = args.keys.map(&:to_sym) -
          handlers.keys.flatten.uniq -
          keys_to_ignore -
          handlers.values
            .select { |handler| handler[:type] != :input }
            .map { |handler| "#{handler[:name]}_attributes".to_sym }

        return {} unless unhandled_keys.any?
        raise(UnhandledKeysError, "#{self.name} received unhandled keys: #{unhandled_keys.join(', ')}.") if strict_mode
        args.select { |key| unhandled_keys.include? key } # only change being the removal of to_sym, which seems to affect the outcome because of the args being a hash with indifferent access
      end
```

**Comment by chawes13** [comment]
@dpikt It doesn't look like this change in behavior is accounted for in the [v3 migration guide](https://github.com/LaunchPadLab/decanter/blob/master/migration-guides/v3.0.0.md).

Was this an intentional change in the rewrite?

@dianacamacho While the README doesn't require this, it does suggest in [basic usage](https://github.com/LaunchPadLab/decanter#basic-usage) to pass in the controller key as opposed to the whole params object. Is that a viable workaround for the app that you're working on currently?

**Comment by dianacamacho** [comment]
@chawes13 That's an option for a specific use case inside a controller, where you know what params you are looking for, but in others - like where decanters are used for decanting external api responses (like a Centaman api response), it would be nice to still be able to ignore values that aren't needed, without having to list every response key (assuming we even know every one). 

Mostly pointing out that it sort of feels like this is something a decanter should continue to allow.

**Comment by dpikt** [comment]
I think when I made this change I wasn't fully understanding why someone would use `strict: true` since I thought it just printed a warning (I didn't realize it omitted the keys too). I'd be in favor of reintroducing a "middle" option (`strict: :ignore`) or adding a separate option `ignore_unhandled_keys: true`, although we would want to show a warning when setting it at the same time as `strict` since they are not interoperable.

**Comment by chawes13** [comment]
My preference is to go with the "middle option". Are there any conventions to adhere to for this approach? Instinctively, I find it a bit odd to introduce a 3-state boolean as opposed to an enum (e.g., `:with_exception`, `:ignore`, or `:pass_through`), but I am also not pulling from a lot of lived experience here.

**Comment by dianacamacho** [comment]
Same with the middle option. I also agree on moving to a more enum-like `strict` state. I'll work this into a PR with the previous version of the unhandled keys method.

**Comment by chawes13** [comment]
@dianacamacho Moving to an enum would definitely require a major release (v4). I've got a few things that I was planning on including in that, so I may ask you to base it off of a v4 branch.

Is there an immediate need for this change on a project? I could be supportive of a "temporary" `:ignore` option that preserves compatibility in a minor release, followed by the breaking change in a separate PR.

**Comment by dianacamacho** [comment]
@chawes13 good point. and yes, i would like to use this for omaha and utah so we can start with the temp ignore option (making strict `true`, `:ignore`, or `false`) and then that can be refactored into enums later in a v4

**Comment by chawes13** [comment]
Love it. Glad you're using this! Let me know what support you need
