### ISSUE TITLE
Replace master with main

### ISSUE THREAD

**Issue by chawes13** [LaunchPadLab/decanter#121]
https://www.bbc.com/news/technology-53050955

**Comment by dianacamacho** [comment]
I only just realized they made the change when adding a new repo the other day. Surprised it's been months since the change and they didn't send out a bigger announcement about it (unless i missed it)

**Comment by chawes13** [comment]
There was a bit of a PR blip on twitter but I think the sense was that it was so overdue that really publicizing it wasn't great press?

**Comment by chawes13** [comment]
Done!
