### ISSUE TITLE
Thoughts on Allowing Negative floats

### ISSUE THREAD

**Issue by latuprez** [LaunchPadLab/decanter#125]
## Feature Description
Not sure if this is a feature or a bug - Right now the Float parser does not allow negative values. I recently worked on a project where we found a bug that any negative values end up being saved as positive values through the float parser.

I got around having to make any changes to FloatParser by making my own Parser - so that's always an option if we want to leave the functionality as is in FloatParser

## Suggested Solution
A quick solution is to change the REGEX global in FloatParser from `REGEX = /(\d|[.])/` to `REGEX = /(\d|[.]|[-])/ `  

## Alternatives Considered / Existing Workarounds
For more custimization, we could perhaps add the ability to accept negatives as an option with code like this:

 ```
class FloatParser < ValueParser
  REGEX = /(\d|[.])/
  REGEX_ALLOW_NEGATIVES = /(\d|[.]|[-])/ 

  allow Float, Integer

  parser do |val, options|
    raise Decanter::ParseError.new 'Expects a single value' if val.is_a? Array
    next if (val.nil? || val === '')
    regex = options[:allow_negatives].present? ? REGEX_ALLOW_NEGATIVES : REGEX
    val.scan(regex).join.try(:to_f)
  end
end
```

**Comment by dianacamacho** [comment]
a float is just a real number with a decimal so i would think it should always allow both negative and positive. changing the regex to allow that makes sense to me. thoughts @inveterateliterate @chawes13 

just realized this is probably also affecting the integer parser, which uses the same regex as float

**Comment by inveterateliterate** [comment]
I'm for updating the regex - I agree with @dianacamacho  sounds like it is more _unexpected_ to have your seemingly negative number return positive rather than wanting to coerce something to a positive number.

**Comment by chawes13** [comment]
Agreed with @dianacamacho and @inveterateliterate.

@latuprez Instead of specifying an option, I think we could accommodate that use case using the existing chaining paradigm with a custom parser. E.g.,

```ruby
class SomeDecanter < Decanter::Base
  input :some_number, [:float, :absolute_value]
end
```
