### ISSUE TITLE
Integer Parser Unexpected Results

### ISSUE THREAD

**Issue by inveterateliterate** [LaunchPadLab/decanter#147]
Went down a decent rabbit hole on this one....

## Environment
- `decanter` version: 4.0.1
- `ruby` version: 3.2.0
- `rails` version: 7.0.8

## Expected Behavior

Wanted to use this parser to save only the digits of an SSN, which could come in the format of `xxx-xx-xxxx` (two dashes), and return just the digits (`xxxxxxxxx`)

## Current Behavior

When I attempted this, I see that it only returns the digits up to the first hash:

https://share.zight.com/2Nu9Xo8O

On further inspection, I see this issue raised and closed as follows:

- https://github.com/LaunchPadLab/decanter/issues/125
- https://github.com/LaunchPadLab/decanter/pull/126

This PR does solve for negative numbers, as the regex is meant to _preserve_ certain characters (rather than strip out). In my attempt to apply this parser, I was hoping it would be able to simply return only digits.

Upon further exploration I think this brings up a couple questions:
1. Should this parser account for floats? It looks to preserve `.` and convert to `Float` if the val is already a float. That feels like a smell
2. Should this parser simply focus on digits, and offer more optionality to handle `-` as indicators of negative values (with a default yes but option for abs values)? I saw something along these lines (albeit in a custom parser) was raised here: https://github.com/LaunchPadLab/decanter/issues/125#issuecomment-970275021

## Steps to Reproduce
- use the IntegerParser with a val that has multiple "accepted" REGEX characters
- https://share.zight.com/2Nu9Xo8O

## Suggested Solution
1. Custom parser (current approach)
2. Refactor this parser towards more flexibility, per question 2 above

**Comment by chawes13** [comment]
@inveterateliterate Can you please elaborate on:
> It looks to preserve . and convert to Float if the val is already a float. That feels like a smell

Thanks!

**Comment by chawes13** [comment]
@inveterateliterate As an aside to this issue, I believe that in the US SSN's can start with 0. This means that using an integer parser is probably not a safe parser to use for this data type (unless you combine it a custom rjust parser).

E.g., "010-12-345" -> "1012345"

Source: https://www.ssa.gov/policy/docs/ssb/v45n11/v45n11p29.pdf

**Comment by chawes13** [comment]
We could potentially explore this regex: `/^-?\d|[\d|.]/`, which would cover your requirements (excluding numbers with leading 0s). However, it wouldn't cover `-.00`, but I don't know if that's a valid use case?

**Comment by inveterateliterate** [comment]
> @inveterateliterate Can you please elaborate on:
> 
> > It looks to preserve . and convert to Float if the val is already a float. That feels like a smell
> 
> Thanks!

It's an integer parser but can handle and return Floats

**Comment by inveterateliterate** [comment]
> @inveterateliterate As an aside to this issue, I believe that in the US SSN's can start with 0. This means that using an integer parser is probably not a safe parser to use for this data type (unless you combine it a custom rjust parser).
> 
> E.g., "010-12-345" -> "1012345"
> 
> Source: https://www.ssa.gov/policy/docs/ssb/v45n11/v45n11p29.pdf

Yup, I think a custom parser for SSN is preferred (fwiw we are storing it as a string). Was just exploring some options to meet some clever client QA.  

Regardless, given my comment about handling `.` and `-` in the regex, should this parser really only focus on scanning digits and provide an option to preserve negatives?

**Comment by inveterateliterate** [comment]
Also I wasn't sure if it was a bug or enhancement, more of a question. Chose bug only because it seemed unexpected, but understand that's partially due to "user error" in a way (misusing)

**Comment by chawes13** [comment]
> It's an integer parser but can handle and return Floats

Ah, I see. Can you remind me of the case where it returns a float?

**Comment by inveterateliterate** [comment]
My bad. My eyes insisted on seeing the word `Float` in line 12 the first 40 times I read it but reading it for the 41st time I see that it's in line 11 in the `if` condition. Can close.
