### ISSUE TITLE
Model Errors

### ISSUE THREAD

**Issue by dshvazz** [LaunchPadLab/decanter#19]
Decanter extensions should catch exceptions (unexpected and from strict :with_exception) and add them as errors on the model. This way, the model will be invalid and they can be displayed to the client with the associated input.

**Comment by francirp** [comment]
I think the value of raising exceptions (at least with regards to ```strict :with_exception```) is that it makes sure developers are aware of unwanted params coming into the decanter. I'm worried adding these errors to the model validations would be sneaky and unclear to developers. Also, how would we handle errors where there is no model attached to the decanter?

**Comment by dshvazz** [comment]
Ohh, i wrote this wrong. What i meant was how to handle 'required' attributes from decanter's point of view, but not the models. For example, if I have 'full_name' in the decanter, but first_name and last_name on the model, what i want is an error on the model for :full_name so i can make the model invalid and show the error to the client correctly.

**Comment by francirp** [comment]
:+1: got it - totally makes sense
