### ISSUE TITLE
DateTime parsing

### ISSUE THREAD

**Issue by wade00** [LaunchPadLab/decanter#20]
I'm trying to pass "10:00 am" to the date_time parser and I'm getting an invalid date error.

It looks like the parser is calling `Date.strptime` on my "10:00 am" string. Should it be using `DateTime.parse` instead?

**Comment by dshvazz** [comment]
The datetime parser currently uses Date.strptime. It should user DateTime and the default format should include the time.

**Comment by dshvazz** [comment]
PR #21 Submitted for @francirp
