### ISSUE TITLE
Update class loading for value parsers

### ISSUE THREAD

**Issue by dshvazz** [LaunchPadLab/decanter#24]
Use the same class loading logic in use with decanters to parser can be found anywhere

**Comment by dshvazz** [comment]
@francirp this needs qa to make sure

**Comment by francirp** [comment]
@dshvazz :+1: so it is the inheritance that triggers Decanter to identify the parser and not the file path?

**Comment by dshvazz** [comment]
its just using constantize

On Wed, Apr 13, 2016 at 11:55 AM, Ryan Francis <notifications@github.com>
wrote:

> @dshvazz <https://github.com/dshvazz> [image: :+1:] so it is the
> inheritance that triggers Decanter to identify the parser and not the file
> path?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/LaunchPadLab/decanter/issues/24#issuecomment-209543755>
>



-- 

*Dave Corwin*
LaunchPad Lab <http://launchpadlab.com/> - Developer
*We Build Apps That Grow Your Business*

tele: 773-405-8401  |  twitter: @davidmcorwin
