### ISSUE TITLE
Rails 5 issue when trying to squash inputs?

### ISSUE THREAD

**Issue by blimey85** [LaunchPadLab/decanter#41]
I'm not sure if this is an issue just because I'm using Rails 5 but I can't seem to get input squashing to work. Below is all of the code I have that is pertinent.

What I'm trying to do seems very simple in theory. I have four pickers on my form. One each for start_date, start_time, end_date, and end_time. They're javascript and do the fancy little popups. That part all works fine. However, in my database I have :starts_at and :ends_at as date time fields that I want to store this data in. I found your gem and it looks perfect for what I'm trying to do. I'm assume I'm up against some issue with strong params but I'm not sure. I've spent several hours trying to crack this and since I don't know what is causing the issue, I'm unsure of how to solve it. Any advice would be much appreciated!

```
class EventDecanter < Decanter::Base
  ignore :waitlist, :status, :type, :visibility, :venue_id

  input :name, :string
  input :description, :string
  input :rsvp_min_limit, :integer
  input :rsvp_max_limit, :integer

  input [:start_date, :start_time], :squash_date_time, key: :starts_at
  input [:end_date, :end_time], :squash_date_time, key: :ends_at
end
```

```
class SquashDateTimeParser < Decanter::Parser::ValueParser
  parser do |value, options|
    date, time = value.map(&:to_s)
    datetime = date + ' ' + time
    datetime.to_datetime
  end
end
```

```
def event_params
      params.require(:event).permit(:name, :description, :starts_at, :ends_at, :start_date, :start_time, :end_date, :end_time, :rsvp_count, :rsvp_min_limit, :rsvp_max_limit, :waitlist, :waitlist_count, :status, :type, :visibility, :venue_id)
    end 
```

```
  def create
    @event = Event.decant_new(event_params)
    @event.save
    respond_with(@event)
  end 
```

**Comment by blimey85** [comment]
Disregard this. No bug. Works fine in Rails 5. I had attr_accessor set on the two fields and that was causing the issue. I commented out those two lines, as seen below, and now it works great. One the one hand I feel good that I figured it out, on the other hand I feel pretty dumb for making such a rookie mistake.

```
  # attr_accessor :starts_at
  # attr_accessor :ends_at
  attr_accessor :start_date
  attr_accessor :start_time
  attr_accessor :end_date
  attr_accessor :end_time
```

**Comment by francirp** [comment]
@blimey85 no problem - I'm glad you still posted because other people may come across the same problem at some point.

Looks like a solid solution you came up with there. I often use the squashing feature for dates as well.

Also, just an FYI, you don't need to use strong_params if you don't want to. Decanter by default will only allow params defined in your Decanter through to your model. I often use the following pattern:

```ruby
  def create
    @event = Event.new(event_params)
    @event.save
    respond_with(@event)
  end

  private

  def event_params
    @event_params ||= EventDecanter.decant(params[:event])
  end
```

Hope you enjoy using Decanter and don't hesitate to reach out with any more issues/questions.

**Comment by francirp** [comment]
Also - @blimey85 please star if you like using Decanter and we would really appreciate if you could share with any of your developer friends that you think could benefit from it. 

I usually just send people the below Medium post to introduce them to it, but the Readme is also pretty good.
https://medium.com/launchpad-lab/the-missing-step-in-rails-controllers-82aaa9172165
