### ISSUE TITLE
Publish a 1.0 version?

### ISSUE THREAD

**Issue by ijdickinson** [LaunchPadLab/decanter#51]
I can see from the releases on Github that you've gone to 1.0. Congrats on that! The latest version on Rubygems is 0.9.2 from August. Are you likely to publish 1.x soon, or would it better to use a `github:` URL in my `Gemfile` for now?

**Comment by francirp** [comment]
@ijdickinson good catch - I never did release the latest version after it was merged. Just released it to Rubygems. Let me know if you have any issues!
