### ISSUE TITLE
Skip Decanter on _destroy = true

### ISSUE THREAD

**Issue by inveterateliterate** [LaunchPadLab/decanter#67]
Decanter was still checking fields even when trying to destroy an object (a nested form object with _destroy set to true). This was an issue when a date field was cleared out before submitting the destroy and Decanter was claiming an "invalid date". 

Maybe this is desired behavior and it's up to the developer to manage incoming params on destroy, maybe decanter can take care of it. Up for discussion.

**Comment by francirp** [comment]
Interesting thought.

I wonder if the bigger issue here is that an empty date returns `invalid date`. I would think an empty date would just be passed through as `nil`.

We could also provide a way for the developer to specify logic around "skipping" parsing.

For example, skip parsing if an attribute is present:
`skip_parsers_if_present '_destroy'`

This could also be a configuration setting in the initializer if one wanted to always skip parsing if an attribute is present (probably common for most Rails apps to skip parsing when _destroy is present).

I'm just not sure this functionality is needed if the parser properly passed through empty state...

**Comment by dpikt** [comment]
@inveterateliterate has this problem popped up again since you opened this issue?

**Comment by dpikt** [comment]
Just chatted with @inveterateliterate about this, it hasn't been an issue for a while so I'll mark it closed for now.
