### ISSUE TITLE
Ignore inputs that aren't sent (instead of setting to nil)

### ISSUE THREAD

**Issue by francirp** [LaunchPadLab/decanter#70]
This is new as of 2.1.0 (was not an issue in 1.1.8).

Let's say we have a TripDecanter:

```ruby
class TripDecanter < Decanter::Base
  input :name, :string
  input :description, :string
end
```

If a param is not passed, Decanter is returning nil for the value like so:

```ruby
TripDecanter.decant(name: 'My Trip')
# => { name: 'My Trip', description: nil }
```

Shouldn't it omit the value from the response like below?

```ruby
# => { name: 'My Trip' }
```

The practical implication of this issue is that we are unable to pass specific attributes to update but instead must always pass the full object.

**Comment by dpikt** [comment]
@francirp I wasn't able to reproduce this locally in the console:
<img width="317" alt="Screen Shot 2019-08-07 at 2 08 41 PM" src="https://user-images.githubusercontent.com/7283471/62650652-f6105880-b91c-11e9-93a3-969cca0c6928.png">
Can you add more details about how to reproduce it?

**Comment by francirp** [comment]
Hmm. Are you using version 2.1.0?

I just recreated using the below example with 2.1.0:

![](https://cl.ly/b3c53f9ceb3a/Screen%20Shot%202019-08-08%20at%201.58.46%20PM.png)
![](https://cl.ly/d4a36857c532/Screen%20Shot%202019-08-08%20at%201.57.02%20PM.png)

**Comment by dpikt** [comment]
@francirp 🤦‍♂ I was using the rails template, but I forgot we pinned decanter to ~> 1 there for this very reason. Can reproduce it now. Thank you for your patience 😀

**Comment by francirp** [comment]
👍 all good man - probably smart to keep it pinned to 1 until we resolve this issue. Thanks for double checking!

**Comment by dpikt** [comment]
Ok, I was able to track down the issue. However, I'm having a really difficult time wrestling with the tests as written. There's a bunch of stubs and mocks and the tests seem like they know way too much about how the class works under the hood. (It's taken me a lot longer to figure out how to test this bug than how to fix it!) How would you feel about refactoring these to be more e2e? Or, at least, writing new tests in a more e2e style?
