### ISSUE TITLE
Write end-to-end specs for key features

### ISSUE THREAD

**Issue by inveterateliterate** [LaunchPadLab/decanter#71]
re-review, update documentation or patch

cc @dpikt

**Comment by dpikt** [comment]
@inveterateliterate can you recall the specific issue you ran into with v2?

**Comment by dpikt** [comment]
Looks like this is one: https://github.com/LaunchPadLab/decanter/issues/70#issue-422490344

**Comment by dpikt** [comment]
@inveterateliterate as we discussed, I'm going to enumerate a list of "core" features and write end-to-end tests for them to give us more confidence in migrating to v2. I'll add that list here before writing tests.

**Comment by dpikt** [comment]
@francirp @inveterateliterate per our discussion last week, let's focus new specs on v1, with eyes on a v3 down the line.

**Comment by dpikt** [comment]
Will be handled on case-by-case basis for v3.
