### ISSUE TITLE
Handle (top level) collection of objects

### ISSUE THREAD

**Issue by inveterateliterate** [LaunchPadLab/decanter#98]
if `params =  { donations: [{ …donation attributes here }] }` I'd like t be able to call something like `DonationDecanter.decant(params[:donations])` and have it decant the collection of individual donation_params

**Comment by chawes13** [comment]
Would the following meet your needs? Or are you requesting for a syntactic enhancement to avoid some of the boilerplate?
```ruby
class DonationDecanter < Decanter::Base
  input :amount, :float
  # ...
end

class DonationCollectionDecanter < Decanter::Base
  has_many :donations
end

# In a controller
donations = DonationCollectionDecanter.decant(params)[:donations]
```

**Comment by inveterateliterate** [comment]
yeah @chawes13 that is a viable approach we considered, but it would be nice if decanter was smart enough to handle that.

**Comment by dpikt** [comment]
This would match the behavior of fast_jsonapi. Decanter could probably be more naive about collection detection as well: https://github.com/Netflix/fast_jsonapi#control-over-collection-serialization

**Comment by chawes13** [comment]
PRs welcome!
